// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZW4O2xwr2ZcL8C3Yr4Ylt-4oNwIilIsE',
    appId: '1:814709178441:web:3c3f5740d2f5d3d4bd7f98',
    messagingSenderId: '814709178441',
    projectId: 'bagboutique-99c03',
    authDomain: 'bagboutique-99c03.firebaseapp.com',
    storageBucket: 'bagboutique-99c03.firebasestorage.app',
    measurementId: 'G-JNY2CM2D40',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAhs4jCY_qvXtl8U6nHBOCTP0_S-6Zdsw',
    appId: '1:814709178441:android:970db48419b85be6bd7f98',
    messagingSenderId: '814709178441',
    projectId: 'bagboutique-99c03',
    storageBucket: 'bagboutique-99c03.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhxHwtrsNHMNf20A6i3pejTSCRuWPEPrE',
    appId: '1:814709178441:ios:3d5e37205d792ee4bd7f98',
    messagingSenderId: '814709178441',
    projectId: 'bagboutique-99c03',
    storageBucket: 'bagboutique-99c03.firebasestorage.app',
    iosBundleId: 'com.example.bagAppFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhxHwtrsNHMNf20A6i3pejTSCRuWPEPrE',
    appId: '1:814709178441:ios:3d5e37205d792ee4bd7f98',
    messagingSenderId: '814709178441',
    projectId: 'bagboutique-99c03',
    storageBucket: 'bagboutique-99c03.firebasestorage.app',
    iosBundleId: 'com.example.bagAppFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZW4O2xwr2ZcL8C3Yr4Ylt-4oNwIilIsE',
    appId: '1:814709178441:web:6f7ce8fef2a56da2bd7f98',
    messagingSenderId: '814709178441',
    projectId: 'bagboutique-99c03',
    authDomain: 'bagboutique-99c03.firebaseapp.com',
    storageBucket: 'bagboutique-99c03.firebasestorage.app',
    measurementId: 'G-S51RY31XW9',
  );
}
